name: CustomWelcomePlugin
version: '1.0-APLHA'
main: me.customWelcomePlugin.CustomWelcomePlugin
api-version: '1.13'
authors: [ AbdelrahmanMoharram, Ahmedabk ]
description: A custom Welcome Plugin and LobbyPlugin not else
commands:
  setlobby:
    description: Sets the current location as the lobby.
    usage: /setlobby
    permission: customwelcomeplugin.setlobby

  lobby:
    description: Teleports the player to the lobby location.
    usage: /lobby
    permission: customwelcomeplugin.lobby

  l:
    description: Shortcut for /lobby command.
    usage: /l
    permission: customwelcomeplugin.lobby

  launchfireball:
    description: Launches a fireball.
    usage: /launchfireball
    permission: customwelcomeplugin.launchfireball

permissions:
  customwelcomeplugin.setlobby:
    description: Allows the player to set the lobby location.
    default: op

  customwelcomeplugin.lobby:
    description: Allows the player to teleport to the lobby.
    default: true  # Allows all players to use it by default

  customwelcomeplugin.launchfireball:
    description: Allows the player to launch a fireball.
    default: op  # Only ops by default, but can be granted to specific players