name: CustomWelcomePlugin
version: '1.0-APLHA'
main: me.customWelcomePlugin.CustomWelcomePlugin
api-version: '1.13'
authors: [ AbdelrahmanMoharram, Ahmedabk ]
description: A custom Welcome Plugin and LobbyPlugin not else
commands:
  setlobby:
    description: Set the lobby spawn point
    permission: customwelcomeplugin.setlobby
  lobby:
    description: Teleport to the lobby
    permission: customwelcomeplugin.lobby
  launchFirework:
    description: Launch a firework at your location
    permission: customwelcomeplugin.launchfirework
  reload:
    description: Reload plugin configurations
    permission: customwelcomeplugin.reload
permissions:
  customwelcomeplugin.setlobby:
    description: Allows the player to set the lobby location
    default: op
  customwelcomeplugin.lobby:
    description: Allows the player to teleport to the lobby
    default: true
  customwelcomeplugin.launchfirework:
    description: Allows the player to launch fireworks
    default: true
  customwelcomeplugin.reload:
    description: Allows the player to reload the plugin configuration
    default: op